# chart: elasticsearch 7.17.3
---
esJavaOpts: -Xmx1g -Xms1g
minimumMasterNodes: 1
replicas: 1
resources:
  requests:
    cpu: 500m
    memory: 1Gi
volumeClaimTemplate:
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn

