# chart: kibana 7.17.3
---
ingress:
  enabled: true
  hosts:
  - host: kibana-dwh.bnctl.develop
    paths:
    - path: /
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

