apiVersion: v1
data:
  core-site.xml: "<configuration>\n  <property>\n    <name>fs.s3a.endpoint</name>\n\
    \    <value>http://minio.bnctl-minio-development-ns.svc.cluster.local:9000</value>\n\
    \  </property>\n  <property>\n    <name>fs.s3a.access.key</name>\n    <value>minioadmin</value>\n\
    \  </property>\n  <property>\n    <name>fs.s3a.secret.key</name>\n    <value>minio-secret-key-change-me</value>\n\
    \  </property>\n  <property>\n    <name>fs.s3a.path.style.access</name>\n    <value>true</value>\n\
    \  </property>\n  <property>\n    <name>fs.s3a.connection.ssl.enabled</name>\n\
    \    <value>false</value>\n  </property>\n  <property>\n    <name>fs.s3a.impl</name>\n\
    \    <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>\n  </property>\n  <property>\n\
    \    <name>fs.s3a.aws.credentials.provider</name>\n    <value>org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider</value>\n\
    \  </property>\n  <property>\n    <name>dremio.s3.compat</name>\n    <value>true</value>\n\
    \  </property>\n</configuration>\n"
  hive-site.xml: "<configuration>\n  <property>\n    <name>hive.metastore.uris</name>\n\
    \    <value>thrift://hive-metastore.bnctl-hive-development-ns.svc.cluster.local:9083</value>\n\
    \  </property>\n  <property>\n    <name>hive.metastore.warehouse.dir</name>\n\
    \    <value>s3a://hive-warehouse/</value>\n  </property>\n</configuration>\n"
  metastore-site.xml: "<configuration>\n  <property>\n    <name>javax.jdo.option.ConnectionDriverName</name>\n\
    \    <value>org.postgresql.Driver</value>\n  </property>\n\n  <property>\n   \
    \ <name>javax.jdo.option.ConnectionURL</name>\n    <value>jdbc:postgresql://cluster-postgresql-primary.bnctl-postgres-development-ns.svc.cluster.local:5432/hive_metastore</value>\n\
    \  </property>\n\n  <property>\n    <name>javax.jdo.option.ConnectionUserName</name>\n\
    \    <value>hive_user</value>\n  </property>\n\n  <property>\n    <name>javax.jdo.option.ConnectionPassword</name>\n\
    \    <value>hive_password</value>\n  </property>\n\n  <property>\n    <name>datanucleus.schema.autoCreateAll</name>\n\
    \    <value>true</value>\n  </property>\n\n  <property>\n    <name>hive.metastore.schema.verification</name>\n\
    \    <value>false</value>\n  </property>\n\n  <property>\n    <name>metastore.thrift.port</name>\n\
    \    <value>9083</value>\n  </property>\n  <property>\n    <name>metastore.expression.proxy</name>\n\
    \    <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>\n\
    \  </property>\n  <property>\n    <name>metastore.task.threads.always</name>\n\
    \    <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>\n\
    \  </property>\n</configuration>\n"
kind: ConfigMap
metadata:
  name: metastore-cfg
  namespace: bnctl-hive-development-ns
