apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: bnctl-hive-development-ns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hive-metastore
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hive-metastore
    spec:
      containers:
      - env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: hive-metastore-secret
        image: tranconggg/hive-metastore:v2
        imagePullPolicy: IfNotPresent
        name: hive-metastore
        ports:
        - containerPort: 9083
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml
          name: metastore-cfg-vol
          subPath: metastore-site.xml
        - mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf/hive-site.xml
          name: metastore-cfg-vol
          subPath: hive-site.xml
        - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          name: metastore-cfg-vol
          subPath: core-site.xml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: metastore-cfg
        name: metastore-cfg-vol

