# chart: postgresql 18.0.11
---
architecture: replication
auth:
  postgresPassword: jRj3VC7kdjMFiWzV8QpvFwhc8
  replicationAllowedHosts: 0.0.0.0/0
  replicationPassword: replication_password_secure
  replicationUser: rep_user
primary:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - postgresql
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - cluster
        topologyKey: kubernetes.io/hostname
  configuration: 'max_connections = 150

    listen_addresses = ''*''

    '
  initdb:
    scripts:
      init_custom_users_and_dbs.sh: "#!/bin/bash\nset -e\n\n# Sử dụng biến POSTGRES_PASSWORD\
        \ thay vì đọc file\nPGPASSWORD=\"$POSTGRES_PASSWORD\" psql -v ON_ERROR_STOP=1\
        \ --username \"postgres\" --dbname \"postgres\" <<-EOSQL\n  -- === Tạo user\
        \ và database cho Airbyte ===\n  CREATE USER airbyte WITH PASSWORD 'bBHAjJAu21ck2348'\
        \ CREATEDB;\n  CREATE DATABASE airbyte OWNER airbyte;\n  CREATE DATABASE temporal\
        \ OWNER airbyte;\n  CREATE DATABASE temporal_visibility OWNER airbyte;\n\n\
        \  -- === Tạo user và database cho N8N ===\n  CREATE ROLE n8n_user LOGIN PASSWORD\
        \ 'JAu21348cbBHAjk2';\n  CREATE DATABASE n8n_db OWNER n8n_user;\n\n  -- ===\
        \ Tạo user và database cho Dolphin ===\n  CREATE ROLE dolphin_user LOGIN PASSWORD\
        \ 'u8cbBHAjk22JA1234';\n  CREATE DATABASE dolphin_db OWNER dolphin_user;\n\
        \n  CREATE ROLE kong LOGIN PASSWORD 'u8ck22JA1234bBHAj';\n  CREATE DATABASE\
        \ kong OWNER kong;\nEOSQL\n\n# Cấp quyền cho database 'airbyte'\nPGPASSWORD=\"\
        $POSTGRES_PASSWORD\" psql -v ON_ERROR_STOP=1 --username \"postgres\" --dbname\
        \ \"airbyte\" <<-EOSQL\n  GRANT CONNECT ON DATABASE airbyte TO airbyte;\n\
        \  GRANT USAGE, CREATE ON SCHEMA public TO airbyte;\n  ALTER SCHEMA public\
        \ OWNER TO airbyte;\n  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL\
        \ ON TABLES TO airbyte;\n  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT\
        \ ALL ON SEQUENCES TO airbyte;\n  ALTER DEFAULT PRIVILEGES IN SCHEMA public\
        \ GRANT ALL ON FUNCTIONS TO airbyte;\nEOSQL\n\n# Cấp quyền cho database 'n8n_db'\n\
        PGPASSWORD=\"$POSTGRES_PASSWORD\" psql -v ON_ERROR_STOP=1 --username \"postgres\"\
        \ --dbname \"n8n_db\" <<-EOSQL\n  GRANT CONNECT ON DATABASE n8n_db TO n8n_user;\n\
        \  GRANT USAGE, CREATE ON SCHEMA public TO n8n_user;\n  ALTER SCHEMA public\
        \ OWNER TO n8n_user;\n  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL\
        \ ON TABLES TO n8n_user;\n  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT\
        \ ALL ON SEQUENCES TO n8n_user;\n  ALTER DEFAULT PRIVILEGES IN SCHEMA public\
        \ GRANT ALL ON FUNCTIONS TO n8n_user;\nEOSQL\n\n# Cấp quyền cho database 'dolphin_db'\n\
        PGPASSWORD=\"$POSTGRES_PASSWORD\" psql -v ON_ERROR_STOP=1 --username \"postgres\"\
        \ --dbname \"dolphin_db\" <<-EOSQL\n  GRANT CONNECT ON DATABASE dolphin_db\
        \ TO dolphin_user;\n  GRANT USAGE, CREATE ON SCHEMA public TO dolphin_user;\n\
        \  ALTER SCHEMA public OWNER TO dolphin_user;\n  ALTER DEFAULT PRIVILEGES\
        \ IN SCHEMA public GRANT ALL ON TABLES TO dolphin_user;\n  ALTER DEFAULT PRIVILEGES\
        \ IN SCHEMA public GRANT ALL ON SEQUENCES TO dolphin_user;\n  ALTER DEFAULT\
        \ PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO dolphin_user;\nEOSQL\n\
        \n# === (MỚI) Cấp quyền cho database 'kong' ===\nPGPASSWORD=\"$POSTGRES_PASSWORD\"\
        \ psql -v ON_ERROR_STOP=1 --username \"postgres\" --dbname \"kong\" <<-EOSQL\n\
        \  GRANT CONNECT ON DATABASE kong TO kong;\n  GRANT USAGE, CREATE ON SCHEMA\
        \ public TO kong;\n  ALTER SCHEMA public OWNER TO kong;\n  ALTER DEFAULT PRIVILEGES\
        \ IN SCHEMA public GRANT ALL ON TABLES TO kong;\n  ALTER DEFAULT PRIVILEGES\
        \ IN SCHEMA public GRANT ALL ON SEQUENCES TO kong;\n  ALTER DEFAULT PRIVILEGES\
        \ IN SCHEMA public GRANT ALL ON FUNCTIONS TO kong;\nEOSQL\n"
  persistence:
    size: 5Gi
    storageClass: longhorn
  resources:
    limits:
      cpu: 1024m
      memory: 2048Mi
    requests:
      cpu: 512m
      memory: 1024Mi
  service:
    nodePorts:
      postgresql: '31432'
    type: NodePort
readReplicas:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - postgresql
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - cluster
        topologyKey: kubernetes.io/hostname
  persistence:
    size: 5Gi
    storageClass: longhorn
  replicaCount: 2
  resources:
    limits:
      cpu: 1024m
      memory: 2048Mi
    requests:
      cpu: 512m
      memory: 1024Mi

