# chart: dremio 3.0.13
# repo: https://bitnami.com
---
coordinator:
  extraEnvVars:
  - name: DREMIO_MAX_HEAP_SIZE_MB
    value: 4096Mi
  persistence:
    enabled: true
    size: 5Gi
    storageClass: longhorn
  replicaCount: 1
  resources:
    limits:
      cpu: 2
      memory: 4096Mi
    requests:
      cpu: 1
      memory: 4096Mi
defaultInitContainers:
  copyDefaultConf:
    enabled: true
  defaultImage:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnamilegacy/os-shell
    tag: 12-debian-12-r51
  generateConf:
    enabled: true
  initCerts:
    enabled: true
  upgradeKeystore:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      enabled: true
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
      seLinuxOptions: {}
      seccompProfile:
        type: RuntimeDefault
    enabled: true
  wait:
    enabled: true
dremio:
  image:
    digest: ''
    registry: docker.io
    repository: bitnamilegacy/dremio
    tag: 26.0.0-debian-12-r5
executor:
  common:
    extraEnvVars:
    - name: DREMIO_MAX_HEAP_SIZE_MB
      value: 2048Mi
    persistence:
      enabled: true
      size: 5Gi
      storageClass: longhorn
    replicaCount: 1
    resources:
      limits:
        cpu: 2
        memory: 4096Mi
      requests:
        cpu: 1
        memory: 2048Mi
externalS3:
  accessKeyID: minioadmin
  accessKeySecret: minio-secret-key-change-me
  authentication: accesskey
  bucket: dremio
  disableCertChecking: true
  host: minio.bnctl-minio-development-ns.svc.cluster.local
  path: /dremio
  port: 9000
  protocol: http
  region: us-east-1
ingress:
  enabled: true
  hostname: dremio-dwh.bnctl.develop
  ingressClassName: nginx
  path: /
  pathType: Prefix
  tls: true
masterCoordinator:
  extraEnvVars:
  - name: DREMIO_MAX_HEAP_SIZE_MB
    value: 4096Mi
  persistence:
    enabled: true
    size: 10Gi
    storageClass: longhorn
  replicaCount: 1
  resources:
    limits:
      cpu: 2
      memory: 4096Mi
    requests:
      cpu: 1
      memory: 4096Mi
minio:
  enabled: false
service:
  nodePorts:
    client: '31100'
    flight: '31220'
    web: '31047'
  ports:
    client: 31010
    flight: 32010
    web: 9047
  type: NodePort
zookeeper:
  containerPorts:
    client: 2181
  enabled: true
  image:
    digest: ''
    registry: docker.io
    repository: bitnamilegacy/zookeeper
    tag: 3.9.3-debian-12-r22
  persistence:
    enabled: true
    size: 2Gi
    storageClass: longhorn
  replicaCount: 1
  resources:
    limits:
      cpu: 2
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 512Mi

