apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: treasury-remittance-parser-spark-job
  namespace: "{{ var.value.get('SPARK_NAMESPACE', 'bnctl-spark2-development-ns') }}"
spec:
  type: Python
  mode: cluster
  image: "haiptjits/spark-3.5.1:v2"
  imagePullPolicy: IfNotPresent
  pythonVersion: "3"
  mainApplicationFile: "s3a://spark-scripts/treasury_remittance_parser_spark.py"
  arguments:
    - "--date"
    - "{{ params.get('PROCESS_DATE', '') }}"
  sparkVersion: "3.5.1"
  sparkConf:
    # JARS CONFIG
    "spark.driver.extraClassPath": "/opt/spark/jars/*"
    "spark.executor.extraClassPath": "/opt/spark/jars/*"
    # ICEBERG CORE CONFIG
    "spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
    "spark.sql.catalog.hive": "org.apache.iceberg.spark.SparkCatalog"
    "spark.sql.catalog.hive.type": "hive"
    "spark.sql.catalog.hive.uri": "{{ var.value.HIVE_METASTORE_URI }}"
    "spark.sql.catalog.hive.warehouse": "s3a://hive-warehouse"
    "spark.sql.defaultCatalog": "hive"
    "spark.sql.warehouse.dir": "s3a://hive-warehouse"
    # ICEBERG I/O CONFIG
    "spark.sql.catalog.hive.io-impl": "org.apache.iceberg.aws.s3.S3FileIO"
    "spark.sql.catalog.hive.s3.endpoint": "{{ conn.minio_conn.extra_dejson.endpoint_url }}"
    "spark.sql.catalog.hive.s3.path-style-access": "true"
    "spark.sql.catalog.hive.client.region": "us-east-1"
    "spark.sql.catalog.hive.s3.access-key-id": "{{ conn.minio_conn.login }}"
    "spark.sql.catalog.hive.s3.secret-access-key": "{{ conn.minio_conn.password }}"
    # HADOOP MINIO CONFIG
    "spark.hadoop.fs.s3a.endpoint": "{{ conn.minio_conn.extra_dejson.endpoint_url }}"
    "spark.hadoop.fs.s3a.access.key": "{{ conn.minio_conn.login }}"
    "spark.hadoop.fs.s3a.secret.key": "{{ conn.minio_conn.password }}"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
  driver:
    cores: {{ var.value.get('SPARK_TREASURY_REMITTANCE_PARSER_DRIVER_CORES') | int }}
    coreRequest: "{{ var.value.get('SPARK_TREASURY_REMITTANCE_PARSER_DRIVER_CORE_REQUEST') }}"
    coreLimit: "{{ var.value.get('SPARK_TREASURY_REMITTANCE_PARSER_DRIVER_CORE_LIMIT') }}"
    memory: "{{ var.value.get('SPARK_TREASURY_REMITTANCE_PARSER_DRIVER_MEMORY') }}"
    serviceAccount: spark-sa
  executor:
    cores: {{ var.value.get('SPARK_TREASURY_REMITTANCE_PARSER_EXECUTOR_CORES') | int }}
    coreRequest: "{{ var.value.get('SPARK_TREASURY_REMITTANCE_PARSER_EXECUTOR_CORE_REQUEST') }}"
    coreLimit: "{{ var.value.get('SPARK_TREASURY_REMITTANCE_PARSER_EXECUTOR_CORE_LIMIT') }}"
    instances: {{ var.value.get('SPARK_TREASURY_REMITTANCE_PARSER_EXECUTOR_INSTANCES') | int }}
    memory: "{{ var.value.get('SPARK_TREASURY_REMITTANCE_PARSER_EXECUTOR_MEMORY') }}"
  restartPolicy:
    type: Never
