name: 't24_silver'
version: '1.0.0'
config-version: 2
profile: 't24_silver'
model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  t24_silver:
    +database: hive
    +root_path: silver
    +schema: silver
    +materialized: table
vars: {business_date: "", target_date: ""}
